name: sumcol CI

on: [push]

jobs:
  run-tests:
    runs-on: [linux]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test